In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [3]:
prices = np.array([1,2,3,4])
T = 2
total_days = len(prices)
[prices[i] - prices[i-T] for i in range(T, total_days)]

[2, 2]

In [4]:
prices = np.array([1,1.05,1.1,1.15,1.20,1.25,1.30])
daily_changes = np.diff(prices)
T = 5
total_days = 6
monthly_changes = np.array([prices[i] - prices[i-T] for i in range(T, total_days)])
monthly_changes

array([0.25])

In [20]:
total_days = 6
daily_returns = [0.05]*total_days
prices2 = [1]
for daily_return in daily_returns:
    prices2.append(prices2[-1] + daily_return)
print(prices2)
daily_changes = np.diff(prices)
print(daily_changes)
monthly_changes = np.array([prices[i] - prices[i-T] for i in range(T, total_days)])
print(monthly_changes)

[1, 1.05, 1.1, 1.1500000000000001, 1.2000000000000002, 1.2500000000000002, 1.3000000000000003]
[0.05 0.05 0.05 0.05 0.05 0.05]
[0.25]


In [22]:
decomposed_D2_t = []
for t in range(T, total_days):
    sum1 = 0
    sum2 = 0
    for u in range(0, T):
        sum1 += daily_changes[t-u]**2
        sum2 += (prices[t-u-1] - prices[t-T]) * daily_changes[t-u]
    decomposed_D2_t.append(sum1 + 2*sum2)
print(decomposed_D2_t)
print(monthly_changes**2)

[0.06250000000000001]
[0.0625]


In [6]:
decomposed_D3_t = []
for t in range(T, total_days):
    sum1 = 0
    sum2 = 0
    sum3 = 0
    for u in range(0, T):
        sum1 += daily_changes[t-u]**3
        sum2 += (prices[t-u-1] - prices[t-T]) * daily_changes[t-u]**2
        sum3 += (prices[t-u-1] - prices[t-T])**2 * daily_changes[t-u]
    decomposed_D3_t.append(sum1 + 3*sum2 + 3*sum3)
print(decomposed_D3_t)
print(monthly_changes**3)

[0.015625000000000007]
[0.015625]


In [7]:
decomposed_D4_t = []
for t in range(T, total_days):
    sum1 = 0
    sum2 = 0
    sum3 = 0
    sum4 = 0
    for u in range(0, T):
        sum1 += daily_changes[t-u]**4
        sum2 += (prices[t-u-1] - prices[t-T]) * daily_changes[t-u]**3
        sum3 += (prices[t-u-1] - prices[t-T])**2 * daily_changes[t-u]**2
        sum4 += (prices[t-u-1] - prices[t-T])**3 * daily_changes[t-u]
    decomposed_D4_t.append(sum1 + 4*sum2 + 6*sum3 + 4*sum4)
print(decomposed_D4_t)
print(monthly_changes**4)

[0.003906250000000002]
[0.00390625]
