In [2]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [3]:
prices = np.array([1,2,3,4])
T = 2
total_days = len(prices)
[prices[i] - prices[i-T] for i in range(T, total_days)]

[2, 2]

In [4]:
prices = np.array([1,1.05,1.1,1.15,1.20,1.25,1.30])
daily_changes = np.diff(prices)
T = 5
total_days = 6
monthly_changes = np.array([prices[i] - prices[i-T] for i in range(T, total_days)])
monthly_changes

array([0.25])

In [29]:
total_days = 5
T = 3
daily_returns = [0.05*i for i in range(1, total_days+1)]
prices = [1]
for daily_return in daily_returns:
    prices.append(prices[-1] + daily_return)
print(prices)
daily_changes = np.diff(prices)
print(daily_changes)
monthly_changes = np.array([prices[i] - prices[i-T] for i in range(T, total_days)])
print(monthly_changes)

[1, 1.05, 1.1500000000000001, 1.3000000000000003, 1.5000000000000002, 1.7500000000000002]
[0.05 0.1  0.15 0.2  0.25]
[0.3  0.45]


In [30]:
decomposed_D2_t = []
for t in range(T, total_days):
    sum1 = 0
    sum2 = 0
    for u in range(0, T):
        sum1 += daily_changes[t-u-1]**2
        sum2 += (prices[t-u-1] - prices[t-T]) * daily_changes[t-u-1]
    decomposed_D2_t.append(sum1 + 2*sum2)
print(decomposed_D2_t)
print(monthly_changes**2)

[0.09000000000000016, 0.20250000000000018]
[0.09   0.2025]


In [31]:
decomposed_D3_t = []
for t in range(T, total_days):
    sum1 = 0
    sum2 = 0
    sum3 = 0
    for u in range(0, T):
        sum1 += daily_changes[t-u-1]**3
        sum2 += (prices[t-u-1] - prices[t-T]) * daily_changes[t-u-1]**2
        sum3 += (prices[t-u-1] - prices[t-T])**2 * daily_changes[t-u-1]
    decomposed_D3_t.append(sum1 + 3*sum2 + 3*sum3)
print(decomposed_D3_t)
print(monthly_changes**3)

[0.027000000000000073, 0.0911250000000001]
[0.027    0.091125]


In [32]:
decomposed_D4_t = []
for t in range(T, total_days):
    sum1 = 0
    sum2 = 0
    sum3 = 0
    sum4 = 0
    for u in range(0, T):
        sum1 += daily_changes[t-u-1]**4
        sum2 += (prices[t-u-1] - prices[t-T]) * daily_changes[t-u-1]**3
        sum3 += (prices[t-u-1] - prices[t-T])**2 * daily_changes[t-u-1]**2
        sum4 += (prices[t-u-1] - prices[t-T])**3 * daily_changes[t-u-1]
    decomposed_D4_t.append(sum1 + 4*sum2 + 6*sum3 + 4*sum4)
print(decomposed_D4_t)
print(monthly_changes**4)

[0.008100000000000029, 0.041006250000000063]
[0.0081     0.04100625]
